### ISSUE TITLE
api_connection compiling error!

### ISSUE THREAD

**Issue by gulersoylular** [3ative/NSPanel-ESPHome-Code#1]
I am getting following error message, when it is compiling,

Compiling .pioenvs/nspanel-lounge/src/esphome/components/api/api_connection.cpp.o
xtensa-esp32-elf-g++: fatal error: Killed signal terminated program cc1plus
compilation terminated.
*** [.pioenvs/nspanel-lounge/src/esphome/components/api/api_connection.cpp.o] Error 1
========================= [FAILED] Took 32.72 seconds =========================

Thanks for support

**Comment by 3ative** [comment]
Not something I can replicate here...

However, from Googling, it seems that error is caused by not having enough RAM on the system you're compiling on.
See here: https://github.com/esphome/issues/issues/3867
