### ISSUE TITLE
compile error whit esphome version starting 2.233

### ISSUE THREAD

**Issue by gepetto666** [3ative/NSPanel-ESPHome-Code#2]

**Comment by gepetto666** [comment]
I haved try to update the firmware from 2023.11.6 to 2023.12.9 and get some confusing error when try to compile.
I attach the yaml and the log. Is not a critical error , i can stay on v11, have reverted the esphome from backup
[logs_ns-panel-hr_run.txt](https://github.com/3ative/NSPanel-ESPHome-Code/files/14241341/logs_ns-panel-hr_run.txt)
[hr.txt](https://github.com/3ative/NSPanel-ESPHome-Code/files/14241354/hr.txt)
Thnks in advance

**Comment by 3ative** [comment]
ESPHome updates... always seem to break my tutorials 😥

Try removing these lines from the yaml:
![image](https://github.com/3ative/NSPanel-ESPHome-Code/assets/51385971/c63f4163-744f-4786-9e73-69459593b5ab)

**Comment by gepetto666** [comment]
Your solution is working.
You can edit example yaml
Thnks and best regards

**Comment by 3ative** [comment]
Excellent. 
Thanks for letting me know. 

I'll leave this open until you fully verify it's AOK.  Please close it if you are happy.

**Comment by gepetto666** [comment]
I have update all device in my network all sems to be ok.
Isue closed 
Thnks
